# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(663, 493)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/adobe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 376))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuExport.setIcon(icon1)
        self.menuExport.setObjectName("menuExport")
        self.menuRecentFiles = QtWidgets.QMenu(self.menuFile)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/recents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuRecentFiles.setIcon(icon2)
        self.menuRecentFiles.setObjectName("menuRecentFiles")
        self.menuNavigate = QtWidgets.QMenu(self.menubar)
        self.menuNavigate.setObjectName("menuNavigate")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        window.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(window)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(window)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setWindowTitle("    Outlines :")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeView = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.dockWidget.setWidget(self.dockWidgetContents)
        window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockSearch = QtWidgets.QDockWidget(window)
        self.dockSearch.setFeatures(QtWidgets.QDockWidget.DockWidgetClosable)
        self.dockSearch.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockSearch.setObjectName("dockSearch")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findBackButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.findBackButton.setObjectName("findBackButton")
        self.horizontalLayout.addWidget(self.findBackButton)
        self.findTextEdit = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.findTextEdit.setObjectName("findTextEdit")
        self.horizontalLayout.addWidget(self.findTextEdit)
        self.findNextButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.findNextButton.setObjectName("findNextButton")
        self.horizontalLayout.addWidget(self.findNextButton)
        self.findCloseButton = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.findCloseButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findCloseButton.setIcon(icon3)
        self.findCloseButton.setIconSize(QtCore.QSize(24, 24))
        self.findCloseButton.setObjectName("findCloseButton")
        self.horizontalLayout.addWidget(self.findCloseButton)
        self.dockSearch.setWidget(self.dockWidgetContents_2)
        window.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockSearch)
        self.openFileAction = QtWidgets.QAction(window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileAction.setIcon(icon4)
        self.openFileAction.setObjectName("openFileAction")
        self.quitAction = QtWidgets.QAction(window)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon5)
        self.quitAction.setObjectName("quitAction")
        self.zoominAction = QtWidgets.QAction(window)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoominAction.setIcon(icon6)
        self.zoominAction.setObjectName("zoominAction")
        self.zoomoutAction = QtWidgets.QAction(window)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomoutAction.setIcon(icon7)
        self.zoomoutAction.setObjectName("zoomoutAction")
        self.prevPageAction = QtWidgets.QAction(window)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevPageAction.setIcon(icon8)
        self.prevPageAction.setObjectName("prevPageAction")
        self.nextPageAction = QtWidgets.QAction(window)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextPageAction.setIcon(icon9)
        self.nextPageAction.setObjectName("nextPageAction")
        self.undoJumpAction = QtWidgets.QAction(window)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/undo-jump.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoJumpAction.setIcon(icon10)
        self.undoJumpAction.setObjectName("undoJumpAction")
        self.saveFileAction = QtWidgets.QAction(window)
        self.saveFileAction.setObjectName("saveFileAction")
        self.toPSAction = QtWidgets.QAction(window)
        self.toPSAction.setIcon(icon)
        self.toPSAction.setObjectName("toPSAction")
        self.docInfoAction = QtWidgets.QAction(window)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.docInfoAction.setIcon(icon11)
        self.docInfoAction.setObjectName("docInfoAction")
        self.actionClear = QtWidgets.QAction(window)
        self.actionClear.setObjectName("actionClear")
        self.pageToImageAction = QtWidgets.QAction(window)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pageToImageAction.setIcon(icon12)
        self.pageToImageAction.setObjectName("pageToImageAction")
        self.menuExport.addAction(self.pageToImageAction)
        self.menuExport.addAction(self.toPSAction)
        self.menuFile.addAction(self.openFileAction)
        self.menuFile.addAction(self.menuRecentFiles.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.docInfoAction)
        self.menuFile.addAction(self.quitAction)
        self.menuNavigate.addAction(self.prevPageAction)
        self.menuNavigate.addAction(self.nextPageAction)
        self.menuNavigate.addAction(self.undoJumpAction)
        self.menuView.addAction(self.zoominAction)
        self.menuView.addAction(self.zoomoutAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuNavigate.menuAction())

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Gospel PDF Viewer"))
        self.menuFile.setTitle(_translate("window", "&File"))
        self.menuExport.setTitle(_translate("window", "Export"))
        self.menuRecentFiles.setTitle(_translate("window", "Recent Files"))
        self.menuNavigate.setTitle(_translate("window", "Navigate"))
        self.menuView.setTitle(_translate("window", "&View"))
        self.toolBar.setWindowTitle(_translate("window", "toolBar"))
        self.dockSearch.setWindowTitle(_translate("window", "Search Text :"))
        self.findBackButton.setText(_translate("window", "Find Back"))
        self.findNextButton.setText(_translate("window", "Find/Next"))
        self.openFileAction.setText(_translate("window", "Open"))
        self.openFileAction.setShortcut(_translate("window", "Ctrl+O"))
        self.quitAction.setText(_translate("window", "Quit"))
        self.quitAction.setShortcut(_translate("window", "Ctrl+Q"))
        self.zoominAction.setText(_translate("window", "Zoom In"))
        self.zoominAction.setShortcut(_translate("window", "Ctrl++"))
        self.zoomoutAction.setText(_translate("window", "Zoom Out"))
        self.zoomoutAction.setShortcut(_translate("window", "Ctrl+-"))
        self.prevPageAction.setText(_translate("window", "Prev Page"))
        self.prevPageAction.setShortcut(_translate("window", "Left"))
        self.nextPageAction.setText(_translate("window", "Next Page"))
        self.nextPageAction.setShortcut(_translate("window", "Right"))
        self.undoJumpAction.setText(_translate("window", "Jump Back"))
        self.undoJumpAction.setShortcut(_translate("window", "Shift+Backspace"))
        self.saveFileAction.setText(_translate("window", "Save"))
        self.saveFileAction.setShortcut(_translate("window", "Ctrl+S"))
        self.toPSAction.setText(_translate("window", "to PostScript"))
        self.docInfoAction.setText(_translate("window", "Document Info"))
        self.actionClear.setText(_translate("window", "clear"))
        self.pageToImageAction.setText(_translate("window", "Page to Image"))

import resources_rc
