# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName(_fromUtf8("window"))
        window.resize(663, 493)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 376))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuExport.setIcon(icon1)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuRecentFiles = QtGui.QMenu(self.menuFile)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/recents.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuRecentFiles.setIcon(icon2)
        self.menuRecentFiles.setObjectName(_fromUtf8("menuRecentFiles"))
        self.menuNavigate = QtGui.QMenu(self.menubar)
        self.menuNavigate.setObjectName(_fromUtf8("menuNavigate"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        window.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(window)
        self.toolBar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        window.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtGui.QDockWidget(window)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetClosable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setWindowTitle(_fromUtf8("    Outlines :"))
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeView = QtGui.QTreeView(self.dockWidgetContents)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout.addWidget(self.treeView)
        self.dockWidget.setWidget(self.dockWidgetContents)
        window.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockSearch = QtGui.QDockWidget(window)
        self.dockSearch.setFeatures(QtGui.QDockWidget.DockWidgetClosable)
        self.dockSearch.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockSearch.setObjectName(_fromUtf8("dockSearch"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.findBackButton = QtGui.QPushButton(self.dockWidgetContents_2)
        self.findBackButton.setObjectName(_fromUtf8("findBackButton"))
        self.horizontalLayout.addWidget(self.findBackButton)
        self.findTextEdit = QtGui.QLineEdit(self.dockWidgetContents_2)
        self.findTextEdit.setObjectName(_fromUtf8("findTextEdit"))
        self.horizontalLayout.addWidget(self.findTextEdit)
        self.findNextButton = QtGui.QPushButton(self.dockWidgetContents_2)
        self.findNextButton.setObjectName(_fromUtf8("findNextButton"))
        self.horizontalLayout.addWidget(self.findNextButton)
        self.findCloseButton = QtGui.QPushButton(self.dockWidgetContents_2)
        self.findCloseButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.findCloseButton.setIcon(icon3)
        self.findCloseButton.setIconSize(QtCore.QSize(24, 24))
        self.findCloseButton.setObjectName(_fromUtf8("findCloseButton"))
        self.horizontalLayout.addWidget(self.findCloseButton)
        self.dockSearch.setWidget(self.dockWidgetContents_2)
        window.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockSearch)
        self.openFileAction = QtGui.QAction(window)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileAction.setIcon(icon4)
        self.openFileAction.setObjectName(_fromUtf8("openFileAction"))
        self.quitAction = QtGui.QAction(window)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon5)
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.zoominAction = QtGui.QAction(window)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/zoomin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoominAction.setIcon(icon6)
        self.zoominAction.setObjectName(_fromUtf8("zoominAction"))
        self.zoomoutAction = QtGui.QAction(window)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/zoomout.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomoutAction.setIcon(icon7)
        self.zoomoutAction.setObjectName(_fromUtf8("zoomoutAction"))
        self.prevPageAction = QtGui.QAction(window)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/prev.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevPageAction.setIcon(icon8)
        self.prevPageAction.setObjectName(_fromUtf8("prevPageAction"))
        self.nextPageAction = QtGui.QAction(window)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextPageAction.setIcon(icon9)
        self.nextPageAction.setObjectName(_fromUtf8("nextPageAction"))
        self.undoJumpAction = QtGui.QAction(window)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/undo-jump.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoJumpAction.setIcon(icon10)
        self.undoJumpAction.setObjectName(_fromUtf8("undoJumpAction"))
        self.saveFileAction = QtGui.QAction(window)
        self.saveFileAction.setObjectName(_fromUtf8("saveFileAction"))
        self.toPSAction = QtGui.QAction(window)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/postscript.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toPSAction.setIcon(icon11)
        self.toPSAction.setObjectName(_fromUtf8("toPSAction"))
        self.docInfoAction = QtGui.QAction(window)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.docInfoAction.setIcon(icon12)
        self.docInfoAction.setObjectName(_fromUtf8("docInfoAction"))
        self.actionClear = QtGui.QAction(window)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.menuExport.addAction(self.toPSAction)
        self.menuFile.addAction(self.openFileAction)
        self.menuFile.addAction(self.menuRecentFiles.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.docInfoAction)
        self.menuFile.addAction(self.quitAction)
        self.menuNavigate.addAction(self.prevPageAction)
        self.menuNavigate.addAction(self.nextPageAction)
        self.menuNavigate.addAction(self.undoJumpAction)
        self.menuView.addAction(self.zoominAction)
        self.menuView.addAction(self.zoomoutAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuNavigate.menuAction())

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        window.setWindowTitle(_translate("window", "Gospel PDF Viewer", None))
        self.menuFile.setTitle(_translate("window", "&File", None))
        self.menuExport.setTitle(_translate("window", "Export", None))
        self.menuRecentFiles.setTitle(_translate("window", "Recent Files", None))
        self.menuNavigate.setTitle(_translate("window", "Navigate", None))
        self.menuView.setTitle(_translate("window", "&View", None))
        self.toolBar.setWindowTitle(_translate("window", "toolBar", None))
        self.dockSearch.setWindowTitle(_translate("window", "Search Text :", None))
        self.findBackButton.setText(_translate("window", "Find Back", None))
        self.findNextButton.setText(_translate("window", "Find/Next", None))
        self.openFileAction.setText(_translate("window", "Open", None))
        self.openFileAction.setShortcut(_translate("window", "Ctrl+O", None))
        self.quitAction.setText(_translate("window", "Quit", None))
        self.quitAction.setShortcut(_translate("window", "Ctrl+Q", None))
        self.zoominAction.setText(_translate("window", "Zoom In", None))
        self.zoominAction.setShortcut(_translate("window", "Ctrl++", None))
        self.zoomoutAction.setText(_translate("window", "Zoom Out", None))
        self.zoomoutAction.setShortcut(_translate("window", "Ctrl+-", None))
        self.prevPageAction.setText(_translate("window", "Prev Page", None))
        self.prevPageAction.setShortcut(_translate("window", "Left", None))
        self.nextPageAction.setText(_translate("window", "Next Page", None))
        self.nextPageAction.setShortcut(_translate("window", "Right", None))
        self.undoJumpAction.setText(_translate("window", "Jump Back", None))
        self.undoJumpAction.setShortcut(_translate("window", "Shift+Backspace", None))
        self.saveFileAction.setText(_translate("window", "Save", None))
        self.saveFileAction.setShortcut(_translate("window", "Ctrl+S", None))
        self.toPSAction.setText(_translate("window", "to PostScript", None))
        self.docInfoAction.setText(_translate("window", "Document Info", None))
        self.actionClear.setText(_translate("window", "clear", None))

import resources_rc
